language: node_js
node_js:
- '12'
branch:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
install:
- npm install
script:
- npm run docs:build
after_success:
- rsync -az ./docs/.vuepress/dist root@104.53.65.214:/root/netease-music/web/dist
