language: node_js
node_js:
- '12'
branch:
  only:
  - master
install:
- npm install
script:
- npm run docs:build
after_success:
- rsync -az ./docs/.vuepress/dist root@104.53.65.214:/root/netease-music/web/dist
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa