language: node_js
node_js:
- '12'
addons:
  ssh_known_hosts:
  - 106.53.65.214
branch:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_d1647fea50de_key -iv $encrypted_d1647fea50de_iv -in deploy_rsa.pub.enc -out deploy_rsa.pub -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa.pub
- ssh-add deploy_rsa.pub
install:
- npm install
script:
- npm run build
after_success:
- rsync -az --delete ./dist root@106.53.65.214:/root/test
