language: node_js
node_js:
- '12'
addons:
  ssh_known_hosts: 104.53.65.214
branch:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in id_rsa.enc -out /tmp/id_rsa -d
- chmod 600 /tmp/id_rsa
install:
- npm install
script:
- npm run build
after_success:
- rsync -az ./dist root@104.53.65.214:/root/netease-music/web/dist